### ISSUE TITLE
The scrollbar is invisible.

### ISSUE THREAD

**Issue by Johnz86** [jstoudt/enscroll#15]
I added the enscroll.js at bottom of the page after jquery in my site. 
There is only one div with class scrollbox, which has height 150px and random Lorem Ipsum text. The scrollbar is not visible. The scrollbox was initialized like this:

<pre> jQuery('.scrollbox').enscroll({
    verticalTrackClass: 'track',
    verticalHandleClass: 'handle'
});
</pre>

When i inspect DOM the .track  and .handle has no width and height. The scrollbar is invisible. What should cause such behaviour?

**Comment by theamith** [comment]
scroll bar not visible with jquery version 3.2.1. to reproduce the issue change jquery version in fiddle http://jsfiddle.net/jstoudt/f2Y5S/?utm_source=website&utm_medium=embed&utm_campaign=f2Y5S

**Comment by alwinpalamattam** [comment]
How to maintain scroll position in enscroll,
It keeps the scroll position on top after every refresh.

**Comment by abhishek-0** [comment]
Isn't there any soluton of this problem? Do we have any updated version of enscroll or something else?
