### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by PatONeil** [jstoudt/enscroll#58]
Is it possible to add jquery ui theme support without modifying the code?

**Comment by jstoudt** [comment]
I'm afraid this plugin was not written with any compatibility to jQuery UI in mind. The goal of this plugin was to provide the ability to style the scrollbars to any theme via CSS. I didn't want to confine anybody implementing this plugin to available jQuery UI themes. And, I didn't think anyone would write their own jQuery UI theme just to style scrollbars generated by this plugin.

It may be possible to configure enscroll to use jQuery UI theme style by configuring the `verticalTrackClass`, `verticalHandleClass` and other similar properties when initializing the plugin on your target element.

**Comment by PatONeil** [comment]
I think your suggestion will work buy putting in jQuery UI theme classes for ui-slider.

Thanks.   I have looked at a lot of other scroller and your is the best.

Pat

**Comment by jstoudt** [comment]
Great. Thanks for the complement. Good luck on your project.
