### ISSUE TITLE
How to remove padding right when scrollbar not present

### ISSUE THREAD

**Issue by vedankita** [jstoudt/enscroll#66]
how to remove padding right when scrollbar not present

**Comment by vedankita** [comment]
@jstoudt can you please give me solution for this

**Comment by jstoudt** [comment]
Hi @vedankita The addPaddingToPane option was added some time back to address this issue. More information can be found here: http://enscrollplugin.com/#documentation

**Comment by vedankita** [comment]
thanks @jstoudt :)
where can i get v. 1.4.1

**Comment by jstoudt** [comment]
@vedankita I think that is a error in the documentation. It should say that it was added in 0.4.1. I'm guessing you don't want an older release, but in case you do, you can find them all here https://github.com/jstoudt/enscroll/tree/master/releases

**Comment by vedankita** [comment]
thanks for solution @jstoudt its working
I am facing problem when there is lots of data in div, that time I want right padding and if less data, no padding should be there at runtime.
Can you please help me for this.
