### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by vaibhav5140** [jstoudt/enscroll#81]
My security tool is blocking one website, and reason its showing is due to one JavaScript file named "enscroll.com/releases/enscroll-0.6.1.min.js". Is this plugin has any internal mechanism to make API calls or load additional resources from "enscroll.com" for certain functionalities

**Comment by jstoudt** [comment]
This project has been deprecated for some years now. The domain encroll.com was never registered by myself or anyone else for this project. The domain encrollplugin.com was once used, but is no longer registered. If you need this file for legacy concerns, you can retrieve it from github here https://github.com/jstoudt/jstoudt.github.io/tree/master/releases

I would copy and serve the file locally. I cannot guarantee any of these files will remain publicly accessible in perpetuity.
